# vim:sw=4:

spacing: &spacing	6
half-space: &halfspace	3

bar:
    height: 26
    location: top
    spacing: *spacing
    background: 222222ff
    font: Recursive Sn Csl St:pixelsize=18
    left:
        - i3:
            sort: native
            anchors:
                string: &i3-defaults
                    text: " {name} "
                    on-click:
                        left: "swaymsg --quiet workspace {name}"
                        wheel-up: "swaymsg --quiet workspace prev"
                        wheel-down: "swaymsg --quiet workspace next"
            content:
                "":
                    map:
                        default: {string: {foreground: 888888ff, <<: *i3-defaults}}
                        conditions:
                            state == focused: {string: {deco: {background: {color: 285577ff}}, <<: *i3-defaults}}
                current: # modes
                    map:
                        default:
                            - empty: {left-margin: *spacing}
                            - string:
                                margin: 8
                                text: "{mode}"
                                deco: {background: {color: aa2222ff}}
                        conditions:
                            mode == default: {empty: {}}
    center:
        - foreign-toplevel:
            content:
                map:
                    conditions:
                        ~activated: {empty: {}}
                        activated:
                            list:
                                spacing: *halfspace
                                items:
                                    # - string: {text: "{app-id}", foreground: ffa0a0ff}
                                    - string: {text: "{app-id}", foreground: 888888ff}
                                    - string: {text: "–", foreground: 888888ff}
                                    - string: {text: "{title}"}
        # - i3:
        #     content:
        #         "": {empty: {}}
        #         current:
        #             list:
        #                 spacing: 4
        #                 items:
        #                     - string:
        #                         text: "{title}"
        #                     - string:
        #                         text: "{application}"
        #                         foreground: 888888ff
        #                         font: Recursive Sn Csl St:pixelsize=16

    right:
        - battery:
            name: BAT0
            poll-interval: 15000
            smoothing-secs: 60
            content:
                map:
                    default:
                        string: &bat-defaults
                            foreground: 888888ff
                            text: "{capacity}% ({estimate})"
                    conditions:
                        state==charging: {string: {<<: *bat-defaults, foreground: 66bb66ff}}
                        capacity > 90: {string: {<<: *bat-defaults, foreground: 66bb66ff}}
                        capacity < 20: {string: {<<: *bat-defaults, foreground: ff4444ff, font: Recursive Sn Csl St:pixelsize=22}}
                        capacity < 30: {string: {<<: *bat-defaults, foreground: ff6666ff, font: Recursive Sn Csl St:pixelsize=20}}
                        capacity < 40: {string: {<<: *bat-defaults, foreground: ff6666ff}}
                        capacity < 45: {string: {<<: *bat-defaults, foreground: ff8888ff}}
                        capacity < 60: {string: {<<: *bat-defaults, foreground: ff8888ff}}  # TODO: yellow.
        - clock:
            date-format: "%a, %d %b %Y"
            content:
                list:
                    spacing: *spacing
                    items:
                        - string: {text: "{date}", font: 'Recursive Sn Csl St:pixelsize=18', foreground: ddddddff}
                        - string: {text: "{time}", font: 'Recursive Sn Csl St:pixelsize=24'}
